import {
  Box,
  Button,
  ButtonText,
  Heading,
  Text,
  VStack,
} from '@gluestack-ui/themed';
import { useState } from 'react';

import { useColorScheme } from '@/components/hooks/useColorScheme';
import { setError } from '@/state/slices/generalSlice';
import { useAppDispatch } from '@/state/store';
import { getBackendUrl } from '@/utils/helpers';
import { useI18n } from '@/utils/i18n';

export default function HomeScreen() {
  const dispatch = useAppDispatch();
  const { t } = useI18n();
  const colorScheme = useColorScheme();
  const isDark = colorScheme === 'dark';
  const [connectionStatus, setConnectionStatus] = useState('');

  const onPressTestErrorModal = () => {
    dispatch(
      setError({
        message: 'This is a test error generated by the ErrorModal demo.',
        name: 'DemoError',
        stack: 'Triggered from the starter home screen.',
        code: 'TEST_ERROR_MODAL',
        statusCode: 500,
      }),
    );
  };

  const onPressTestBackendConnection = async () => {
    const healthUrl = `${getBackendUrl()}/health`;
    setConnectionStatus(t('status.checkingBackend'));

    try {
      const response = await fetch(healthUrl);
      if (!response.ok) {
        throw new Error(`Backend returned HTTP ${response.status}`);
      }

      const result = (await response.json()) as { status?: string };
      setConnectionStatus(
        result.status === 'ok'
          ? t('status.backendSuccess')
          : t('errors.unexpectedBackendStatus'),
      );
    } catch (error) {
      setConnectionStatus(t('errors.backendUnavailable'));
      dispatch(
        setError({
          message:
            error instanceof Error
              ? error.message
              : t('errors.backendRequestFailed'),
          name: 'BackendConnectionError',
        }),
      );
    }
  };

  return (
    <VStack
      flex={1}
      p="$4"
      bg={colorScheme === 'dark' ? '$backgroundDark950' : '$backgroundLight0'}
      space="lg"
    >
      <Heading size="2xl">{t('app.title')}</Heading>
      <Text size="md">{t('app.description')}</Text>

      <Box
        bg={isDark ? '$backgroundDark900' : '$coolGray50'}
        borderRadius="$lg"
        p="$4"
      >
        <Heading
          size="sm"
          mb="$2"
          color={isDark ? '$textDark50' : '$textLight900'}
        >
          {t('checklist.title')}
        </Heading>
        <VStack space="sm">
          <Text color={isDark ? '$textDark50' : '$textLight900'}>
            • {t('checklist.replaceContent')}
          </Text>
          <Text color={isDark ? '$textDark50' : '$textLight900'}>
            • {t('checklist.addRedux')}
          </Text>
          <Text color={isDark ? '$textDark50' : '$textLight900'}>
            • {t('checklist.addScreens')}
          </Text>
        </VStack>
      </Box>

      <Button onPress={onPressTestErrorModal} variant="solid">
        <ButtonText>{t('actions.testErrorModal')}</ButtonText>
      </Button>
      <Button onPress={onPressTestBackendConnection} variant="outline">
        <ButtonText>{t('actions.testBackendConnection')}</ButtonText>
      </Button>
      {connectionStatus ? <Text>{connectionStatus}</Text> : null}
    </VStack>
  );
}
