import { Button, ButtonText, VStack } from '@gluestack-ui/themed';
import { FlashList } from '@shopify/flash-list';
import { useQueryClient } from '@tanstack/react-query';
import { useState } from 'react';

import { ThemeAwareSurface } from '@/components/ui/ThemeAwareSurface';
import {
  ThemeAwareHeading,
  ThemeAwareText,
} from '@/components/ui/ThemeAwareText';
import type { BackendHealth } from '@/features/backend/api';
import {
  backendHealthQueryKey,
  useBackendHealthQuery,
} from '@/features/backend/hooks/useBackendHealthQuery';
import { setError } from '@/state/slices/generalSlice';
import { useAppDispatch } from '@/state/store';
import { useI18n } from '@/utils/i18n';

/*
 * The home screen intentionally uses FlashList even for this small starter
 * dataset so new template screens have a clear list-performance example.
 */
export default function HomeScreen() {
  const dispatch = useAppDispatch();
  const { t } = useI18n();
  const [connectionStatus, setConnectionStatus] = useState('');
  const [cacheStatus, setCacheStatus] = useState('');
  const queryClient = useQueryClient();
  const { refetch: refetchBackendHealth } = useBackendHealthQuery();
  const checklistItems = [
    t('checklist.replaceContent'),
    t('checklist.addRedux'),
    t('checklist.addScreens'),
  ];

  const onPressTestErrorModal = () => {
    dispatch(
      setError({
        message: 'This is a test error generated by the ErrorModal demo.',
        name: 'DemoError',
        stack: 'Triggered from the starter home screen.',
        code: 'TEST_ERROR_MODAL',
        statusCode: 500,
      }),
    );
  };

  const onPressTestBackendConnection = async () => {
    setConnectionStatus(t('status.checkingBackend'));

    try {
      const { data: result, error } = await refetchBackendHealth();
      if (error) {
        throw error;
      }

      setConnectionStatus(
        result?.status === 'ok'
          ? t('status.backendSuccess')
          : t('errors.unexpectedBackendStatus'),
      );
      setCacheStatus(t('status.backendCached'));
    } catch (error) {
      setConnectionStatus(t('errors.backendUnavailable'));
      dispatch(
        setError({
          message:
            error instanceof Error
              ? error.message
              : t('errors.backendRequestFailed'),
          name: 'BackendConnectionError',
        }),
      );
    }
  };

  const onPressReadBackendCache = () => {
    const cachedHealth = queryClient.getQueryData<BackendHealth>(
      backendHealthQueryKey,
    );
    setCacheStatus(cachedHealth ? t('status.cacheHit') : t('status.cacheMiss'));
  };

  const onPressClearBackendCache = () => {
    queryClient.removeQueries({ queryKey: backendHealthQueryKey });
    setCacheStatus(t('status.cacheCleared'));
  };

  return (
    <ThemeAwareSurface flex={1}>
      <FlashList
        contentContainerStyle={{ padding: 16 }}
        data={checklistItems}
        estimatedItemSize={56}
        keyExtractor={(item) => item}
        ListFooterComponent={
          <VStack space="md" pt="$4">
            <Button onPress={onPressTestErrorModal} variant="solid">
              <ButtonText>{t('actions.testErrorModal')}</ButtonText>
            </Button>
            <Button onPress={onPressTestBackendConnection} variant="outline">
              <ButtonText>{t('actions.testBackendConnection')}</ButtonText>
            </Button>
            <Button onPress={onPressReadBackendCache} variant="outline">
              <ButtonText>{t('actions.readBackendCache')}</ButtonText>
            </Button>
            <Button onPress={onPressClearBackendCache} variant="outline">
              <ButtonText>{t('actions.clearBackendCache')}</ButtonText>
            </Button>
            {connectionStatus ? (
              <ThemeAwareText>{connectionStatus}</ThemeAwareText>
            ) : null}
            {cacheStatus ? (
              <ThemeAwareText>{cacheStatus}</ThemeAwareText>
            ) : null}
          </VStack>
        }
        ListHeaderComponent={
          <VStack space="lg" pb="$2">
            <ThemeAwareHeading size="2xl">{t('app.title')}</ThemeAwareHeading>
            <ThemeAwareText size="md">{t('app.description')}</ThemeAwareText>
            <ThemeAwareHeading size="sm">
              {t('checklist.title')}
            </ThemeAwareHeading>
          </VStack>
        }
        renderItem={({ item }) => (
          <ThemeAwareSurface
            darkBackground="$backgroundDark900"
            lightBackground="$coolGray50"
            borderRadius="$lg"
            mb="$2"
            p="$4"
          >
            <ThemeAwareText>• {item}</ThemeAwareText>
          </ThemeAwareSurface>
        )}
      />
    </ThemeAwareSurface>
  );
}
