export enum Routes {
  AccountScreen = 'AccountScreen',
  BffServiceTestScreen = 'BffServiceTestScreen',
  CookingInstructionsScreen = 'CookingInstructionsScreen',
  DevOptionsScreen = 'DevOptionsScreen',
  FullscreenImageScreen = 'FullscreenImageScreen',
  InventoryLocationModal = 'InventoryLocationModal',
  InventoryScreen = 'InventoryScreen',
  InventoryScreenItem = 'InventoryScreenItem',
  ItemModal = 'itemModal',
  ItemsScreen = 'ItemsScreen',
  MutuallyExclusiveCreatorScreen = 'MutuallyExclusiveCreatorScreen',
  OptionsScreen = 'OptionsScreen',
  PasswordResetScreen = 'PasswordResetScreen',
  QuickAddModal = 'QuickAddModal',
  ScannerScreen = 'ScannerScreen',
  ShareIntentScreen = 'ShareIntentScreen',
  ShoppingList = 'ShoppingList',
  ShoppingListScreen = 'index',
  StoreModal = 'StoreModal',
  StoreScreen = 'StoreScreen',
}
