export enum Routes {
  AccountScreen = 'AccountScreen',
  BffServiceTestScreen = 'BffServiceTestScreen',
  DevOptionsScreen = 'DevOptionsScreen',
  FullscreenImageScreen = 'FullscreenImageScreen',
  ItemModal = 'itemModal',
  ItemsScreen = 'ItemsScreen',
  OptionsScreen = 'OptionsScreen',
  PasswordResetScreen = 'PasswordResetScreen',
  ScannerScreen = 'ScannerScreen',
  ShoppingList = 'ShoppingList',
  ShoppingListScreen = 'index',
  StoreModal = 'StoreModal',
  StoreScreen = 'StoreScreen',
}
