import { XOR } from 'ts-xor';

import { Store } from './Store';
import { SortOrderValue, ListName } from './listSlice';

import { ListFilterFilters } from '@/components/lists/ListFilter';

export type AddedDate = {
  addedDate: number;
};

/**
 *Whether the thing in question needs to be saved in the db
 **/
export type NeedsSaving = {
  needsSaving?: boolean;
};

export enum ItemUnit {
  Bar = 'bar',
  Bunch = 'bunch',
  Can = 'can',
  Case = 'case',
  Cups = 'c',
  Dozen = 'dozen',
  Each = 'ea',
  FluidOunce = 'fl oz',
  Gallon = 'gal',
  Jar = 'jar',
  Kilogram = 'kg',
  Ounce = 'oz',
  Package = 'package',
  Pint = 'pt',
  Pound = 'lb',
  Quart = 'qt',
  Tablespoon = 'tbsp',
  Teaspoon = 'tsp',
  Custom = 'Custom',
}

/**
 *This is the id used to save the item in db.
 *It is generated by the FE when the item is created
 **/
export type Id = {
  _id: string;
};

/**
 *This flag is set when the item has been successfully saved on in the DB
 **/
export type HasBeenSaved = {
  hasBeenSaved?: boolean;
};

export type Key = XOR<
  {
    name: string;
    upc?: string;
  },
  {
    name?: string;
    upc: string;
  }
> &
  Partial<Id>;

export type ItemBase = {
  /**
   *This is in milliseconds
   **/
  frequency?: number;
  fullscreenImage?: string;
  images: string[];
  imageToUseIndex: number;
  inventoryMinimum: number;
  isFrozen?: boolean;
  lastUpdatedDate: number;
  /**
   *This is in milliseconds and it used to determine when the item should should be considered expired after it has been purchased and in the inventory
   **/
  timeToExpiration?: number;
  unit: string;
  url?: string;
};

/**
 *This represents something that can be added to any store
 **/
export type Item = Key & ItemBase & AddedDate & DatabaseItem;
export type DatabaseItem = NeedsSaving & HasBeenSaved & Partial<Id>;
export type ItemWithStoreSpecificValues = Item & StoreSpecificValues;
export type PrevioulsyPurchasedItem = ItemWithStoreSpecificValues & {
  isRecommended: boolean;
};

export enum StoreSpecificValueKey {
  AisleNumber = 'aisleNumber',
  IsInCart = 'isInCart',
  ItemId = 'itemId',
  Note = 'note',
  Price = 'price',
  Quantity = 'quantity',
}

// StoreSpecificValueKeyTypes will now enforce that every enum key is defined
export type StoreSpecificValueKeyTypes = {
  [key in StoreSpecificValueKey]: key extends StoreSpecificValueKey.AisleNumber
    ? number
    : key extends StoreSpecificValueKey.IsInCart
      ? boolean
      : key extends StoreSpecificValueKey.ItemId
        ? string
        : key extends StoreSpecificValueKey.Note
          ? string
          : key extends StoreSpecificValueKey.Price
            ? number
            : key extends StoreSpecificValueKey.Quantity
              ? number
              : never;
};

/**
 *Maps the item key to the store specific values
 **/
export type StoreSpecificValuesMap = { [itemKey: string]: StoreSpecificValues };
export type LastPurchasedMap = {
  [itemKey: string]: StoreSpecificValue<number>;
};

/**
 *These are fields which vary based on the store
 **/
export type StoreSpecificValues = {
  [StoreSpecificValueKey.AisleNumber]?: StoreSpecificValue<string>;
  [StoreSpecificValueKey.IsInCart]?: StoreSpecificValue<boolean>;
  [StoreSpecificValueKey.ItemId]?: StoreSpecificValue<string>;
  [StoreSpecificValueKey.Note]?: StoreSpecificValue<string>;
  [StoreSpecificValueKey.Price]?: StoreSpecificValue<number>;
  [StoreSpecificValueKey.Quantity]?: StoreSpecificValue<number>;
} | null;

export type StoreSpecificValue<T> =
  | { [storeKey: string]: T }
  | null
  | undefined;
export type StoreSpecificValueUpdater = Partial<{
  [key in StoreSpecificValueKey]: (currentValue: any) => any;
}>;

export type LastPurchasedItem = Key & {
  lastPurchaseDate: number;
};

export type List<T> = {
  data: T[];
  sortOrderValue: SortOrderValue;
  filters: ListFilterFilters<T>;
};
export type ListFilters = { [key in ListName]: ListFilterFilters<any> };
export type ItemsList = List<Item>;
export type ShoppingList = List<ItemWithStoreSpecificValues>;
export type LastPurchasedList = List<LastPurchasedItem>;
export type StoreList = List<Store>;
