import {
  Box,
  Button,
  ButtonText,
  Heading,
  Text,
  VStack,
} from '@gluestack-ui/themed';

import { setError } from '@/state/slices/generalSlice';
import { useAppDispatch } from '@/state/store';

export default function HomeScreen() {
  const dispatch = useAppDispatch();

  const onPressTestErrorModal = () => {
    dispatch(
      setError({
        message: 'This is a test error generated by the ErrorModal demo.',
        name: 'DemoError',
        stack: 'Triggered from the starter home screen.',
        code: 'TEST_ERROR_MODAL',
        statusCode: 500,
      }),
    );
  };

  return (
    <VStack flex={1} p="$4" bg="$white" space="lg">
      <Heading size="2xl">Blank Expo Starter</Heading>
      <Text size="md">
        This app is intentionally neutral so you can replace the sample domain
        with your own product flow.
      </Text>

      <Box bg="$coolGray50" borderRadius="$lg" p="$4">
        <Heading size="sm" mb="$2">
          Starter checklist
        </Heading>
        <VStack space="sm">
          <Text>
            • Replace the home screen content with your app landing view
          </Text>
          <Text>• Add your own Redux slices and state patterns</Text>
          <Text>• Add screens, modals, and routes for your product domain</Text>
        </VStack>
      </Box>

      <Button onPress={onPressTestErrorModal} variant="solid">
        <ButtonText>Test ErrorModal</ButtonText>
      </Button>
    </VStack>
  );
}
